### ISSUE TITLE
Zlib deflate compression ?

### ISSUE THREAD

**Issue by sylvainpolletvillard** [browserslist/caniuse-lite#1]
Hi Ben,

I was playing around the source and thought about how to compress it further. Did you think about using a compression algorithm like gzip or deflate ? We have [zlib](https://nodejs.org/api/zlib.html) built-in in Node that provides that. I [made some tests](https://github.com/sylvainpolletvillard/caniuse-lite/commit/dbcef2c844fd29b2769d2912087a5bfaa6735408) and got these results for data folder size :
- original: 895 267 bytes
- gzip: 390 530 bytes
- deflate: 382 478 bytes

43% compression rate looks pretty good to me :+1:

The caveat is that you can't `require()` raw deflate data, so the unpacker needs a refactor. I don't think it implies API breaking changes though, but I don't know much about how the raw data is currently used. Also, we need an alternative to `zlib` for usage in the browser, like [pako](https://github.com/nodeca/pako)

**Comment by ben-eb** [comment]
Hi @sylvainpolletvillard,

Yep, but for client-side usage (one of the main reasons for using this module), we send JS already minified and gzipped. You can see that the bundle script (`npm run bundle`) measures it via gzip size already. It's not the whole module, but a subset of it. If possible I'd like that to measure both caniuse-db and caniuse-lite but I haven't really had the time.

I think minifying on disk is enough, I am pretty sure that npm packs archives with similar techniques so I don't think we need to worry about it.

**Comment by sylvainpolletvillard** [comment]
Right, this does not provide additional value for download times. But I was thinking about the disk usage and the size of node_modules folder, once the data is retrieved, unzipped and stored on disk. That's what I meant by terabytes saved in the long run.

**Comment by ai** [comment]
It is good question about size vs. performance. Maybe you can make benchmark to show how many time we will loose to uncompress data on every `require`.

Of course, right now we “uncompress” it too, bit it is simple and fast algorithm. So question in balance.

**Comment by sylvainpolletvillard** [comment]
I think its very fast considering that browsers do it all the time without anyone noticing.

I'm not a benchmark expert so correct me if [this one](https://github.com/sylvainpolletvillard/caniuse-lite/blob/master/benchmark/inflate.js) is stupid. I got `inflate: 1.433ms` for one file `data/agents.js`

**Comment by ai** [comment]
Benchmark is not perfect but OK for first case. And what is time without deflate?

**Comment by sylvainpolletvillard** [comment]
I only measured the additional cost of the decompression operation. If you want to measure the time for file reading and parsing, it really depends on how and where the files are stored.

**Comment by ai** [comment]
I think it is too complicated. Let’s keep it as it.
