### ISSUE TITLE
Unexpected removal of files

### ISSUE THREAD

**Issue by alexandernst** [browserslist/caniuse-lite#101]
Commit `b70c64156792a9695242991ed63ebee6ab860da4` (version [1.0.30001394](https://github.com/browserslist/caniuse-lite/commit/b70c64156792a9695242991ed63ebee6ab860da4)) seems to have removed quite some files. Was this intentional?

**Comment by ZoranRavic** [comment]
Duplicate of #100

**Comment by eglove** [comment]
I have builds failing:

Error: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'

**Comment by J-C-L-G** [comment]
I was about to ask the same thing, NextJS project failing due to `data/features/css-unicode-bidi.js`

**Comment by ZoranRavic** [comment]
Guys just install the previous version `caniuse-lite@1.0.30001393` like I did.
