### ISSUE TITLE
Symbols feature missing

### ISSUE THREAD

**Issue by metalix2** [browserslist/caniuse-lite#107]
Hello, 

I've noticed that the `symbols` feature is no longer being recogonised since [1.0.30001265](https://github.com/browserslist/caniuse-lite/commit/ddf29cdcdaf55a0024c812b34d3846cfe126d3c2) caniuse-lite db.

https://github.com/browserslist/caniuse-lite/blob/v1.0.30001224/data/features/symbols.js

Any reason for this?

**Comment by ai** [comment]
Yes, Can I Use deleted it.

We only re-pack Can I Use data. Report an issue here https://github.com/Fyrd/caniuse/
