### ISSUE TITLE
Object.fromEntries feature is missing 

### ISSUE THREAD

**Issue by js2me** [browserslist/caniuse-lite#108]
Hello !   
Thanks for this powerful tool for detecting feature support !   

Currently I have occured with problem based with missing Object.fromEntries feature   
How can I fix that ? (May be create a PR with this fix)   

Current `caniuse-lite` has the Object.entries feature, but not Object.fromEntries   

![image](https://user-images.githubusercontent.com/16340911/205921336-72e43c61-36ac-4eda-a579-ca5f37381c55.png)
https://github.com/browserslist/caniuse-lite/tree/main/data/features

**Comment by ai** [comment]
Can I Use doesn’t have `Object.fromEntries` data. Website only shows data from MDN.
