### ISSUE TITLE
Error: Loading PostCSS Plugin failed: Cannot find module 'caniuse-lite/data/features/mdn-css-backdrop-pseudo-element'

### ISSUE THREAD

**Issue by bsaoptima** [browserslist/caniuse-lite#117]
I have a simple React Vite app with node version (v18.14.0) and npm version (9.3.1) that I am deploying on Heroku using git push heroku main.

For some reason, today I did some minor changes and when I pushed, this is the error that I was shown:

`remote: [Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /tmp/build_fb8634e4): [Error] Loading PostCSS Plugin failed: Cannot find module 'caniuse-lite/data/features/mdn-css-backdrop-pseudo-element'`
`remote: Error: Loading PostCSS Plugin failed: Cannot find module 'caniuse-lite/data/features/mdn-css-backdrop-pseudo-element'`

Anyone aware of this?

**Comment by ai** [comment]
You need to update `caniuse-lite`

Try `npx update-browserslist-db@latest`

**Comment by ai** [comment]
1. What package manager do you use? `pnpm`, `npm`, `yarn`?
2. Post somewhere your lock file and give me a link

**Comment by bsaoptima** [comment]
1. I am using npm!
2. https://pastebin.com/HV4HJ653

Sorry for the delay I got dragged in a work event! Thank you for the help!

**Comment by ai** [comment]
Everything looks good. Sorry, have no idea.

Maybe you have an issue with `node_modules`. Try to remove `node_modules`, `npm cache clear --force` and install dependencies again.

**Comment by bsaoptima** [comment]
Still not working, I'm not even sure that is a fault on your side. It might be Heroku.

**Comment by ai** [comment]
Maybe it is a problem in Heroku npm cache. Try to find a way to clean cache.

Also double check that you don’t have `yarn.lock` file.

But I checked that library itself work and it does. So very likely that it is a problem in your environment.

**Comment by yordis** [comment]
In my case, I forgot that I had set `resolutions` at the root of the monorepo 🥲. Took me 5 mins to figure it out.

```json5
// maybe you did this!
"resolutions": {
    "caniuse-lite": "1.0.30001525"
  }
```
