### ISSUE TITLE
Why is the caniuse-lite package so big

### ISSUE THREAD

**Issue by createjdd** [browserslist/caniuse-lite#118]
![image](https://github.com/browserslist/caniuse-lite/assets/30922043/31916667-ac73-478b-adf6-10e89d65ea55)
Why is the caniuse-lite package so big

**Comment by ai** [comment]
Because it contains browser support data for all browsers versions and a lot of features.

Also it contains usage statistics data for every country.

But this package compress the data to be 10x smaller than origin `caniuse-db`.
