### ISSUE TITLE
`caniuse-lite` includes features not shown on caniuse.com

### ISSUE THREAD

**Issue by ddbeck** [browserslist/caniuse-lite#119]
Some of the features in https://github.com/Fyrd/caniuse/tree/main/features-json aren't actually shown on caniuse, such as [`css-grid-animation`](https://github.com/Fyrd/caniuse/blob/main/features-json/css-grid-animation.json) (they have `shown: false` set). However, `caniuse-lite` includes these features.

Would you consider omitting those features, or including the `shown` key from caniuse? I'd prefer to be able to use only those features that I can link to on caniuse.com.

**What I expected**
`"css-grid-animation" in lite.features` → `false`
Alternatively: `lite.feature(lite.features["css-grid-animation"]).shown` → `false`

**What I get:**
`"css-grid-animation" in lite.features` → `true`
`lite.feature(lite.features["css-grid-animation"]).shown` → `undefined`

**Comment by ai** [comment]
1. What benefits will we have by omitting them?
2. Are we sure that Autoprefixer and other `caniuse-lite` users don’t use them?

**Comment by dfabulich** [comment]
Seems like including the `shown` key is the best fix here.

**Comment by ddbeck** [comment]
I didn't consider other consumers of this—I don't know who else is using this or why. 🤷 I can see now that it would be a bad choice to omit those features and agree that a better option is to include the `shown` key. 

(Though I'm skeptical that features not shown on caniuse are as well-maintained and accurate as the ones that are—there's going to be a lot fewer eyes on those features.)

**Comment by ai** [comment]
> agree that a better option is to include the shown key.

Does somebody really need a filter to show only features shown on Can I Use. If yes, we can add this key (send PR).

> Though I'm skeptical that features not shown on caniuse are as well-maintained and accurate as the ones that are

It is better than nothing (for the case of Autoprefixer, for instance)
