### ISSUE TITLE
Caniuse-lite Freeze on NPM Install with packages

### ISSUE THREAD

**Issue by Batsave** [browserslist/caniuse-lite#121]
Hello, I would like to create an Issue because since the last Update, it has been impossible to do an NPM Install of my packages without node_modules/caniuse-lite freezing during installation.

I therefore prefer to send you an Issue because I do not think that the problem comes from my initialization but more probably from a problem in your module

I could obviously be wrong but it's been more than 2 hours since I was able to launch my project with 'vite@latest' and each time I try, the Bash crashes on your module

Thank you very much in advance, I remain available for any questions

**Comment by ai** [comment]
We do not have any install scripts. Maybe it is an npm issue?

**Comment by Batsave** [comment]
Yes excuse me, I think my PC must have been tired with several hours of dev, I don't know why, after the 6th try, no problem and the installation of the modules was done in 15 seconds

Excuse me for the disruption
