### ISSUE TITLE
Uncaught ReferenceError after upgrade

### ISSUE THREAD

**Issue by paulschreiber** [browserslist/caniuse-lite#123]
### Description
After upgrading from  1.0.30001553 to 1.0.30001563, my React app started failing with this error:
```
Uncaught ReferenceError: Cannot access 'ROLLBAR_TOKEN' before initialization
```

This doesn't make a lot of sense, as it's totally unrelated, but `git bisect` led me to this commit and reverting it caused the problem to go away.

**Comment by ai** [comment]
Very likely that happens because JS polyfills was changed.

`caniuse-lite` has browsers database for Browserslist queries like `last 2 versions`. Babel uses Browserslist and on `caniuse-lite` you will have a different target browsers (`npx update-browserslist-db` warns you about these changes).
