### ISSUE TITLE
PiWebRadio Project - stuck at "npm install" step

### ISSUE THREAD

**Issue by arut16** [browserslist/caniuse-lite#125]
Hello everyone,

I am building a small internet radio project with a raspberry pi Zero W from [this project by Kevin Castejon.](https://www.piwebradio.kevincastejon.fr/#/installation)
Unfortunately I'm stuck at the "npm install" step.
Error message below.

Can you help me please ? I waited for hours but nothing happened. It stays stuck there. What to do ?

![image](https://github.com/browserslist/caniuse-lite/assets/58274805/19a1ee41-bb07-4714-9fb3-d613647a08f0)

**Comment by ai** [comment]
This warning is not a reason why your `install` script is freezing. Seems like you have a problem in next task which has no output.

**Comment by arut16** [comment]
> This warning is not a reason why your `install` script is freezing. Seems like you have a problem in next task which has no output.

Thanks for your answer ai but what that means ? what i have to do ?

**Comment by ai** [comment]
Try to ask question to StackOverflow or ChatGPT. I can’t help you here.
