### ISSUE TITLE
Inquiry Regarding Trademark and Patent Rights for Your CC-BY-4.0 Licensed Work

### ISSUE THREAD

**Issue by gumingyu6689** [browserslist/caniuse-lite#134]
Hi the author of caniuse-lite,
We are plan to use your open source repo：caniuse-lite, which we understand is licensed under the Creative Commons Attribution 4.0 International License (CC-BY-4.0).

Before we proceed, we want to clarify some  unclear info first. for example ：could you confirm that the work and its use is free of any trademark and patent rights which the Affirmer owns or controls, or did own or did control？

Thank you for your attention to this matter, and we hope to hear from you soon.

**Comment by ai** [comment]
We are just re-pack of Can I Use website. You should ask them (definitely there is no patents, but I am not sure about trademark).
