### ISSUE TITLE
Firefox ESR version

### ISSUE THREAD

**Issue by urikalish** [browserslist/caniuse-lite#136]
Hi,
A few weeks ago, a new Firefox ESR version [128.5.0](https://www.mozilla.org/en-US/firefox/128.5.0/releasenotes/) was released, but browserslist/caniuse-lite shows me version 115 for Firefox ESR. Am I doing something wrong?

**Comment by ai** [comment]
Update `browserslist` version too. We keep ESR version there. The current version have actual data

https://github.com/browserslist/browserslist/blob/main/index.js#L1024
