### ISSUE TITLE
Unknown version 127 of Edge

### ISSUE THREAD

**Issue by ivanovych666** [browserslist/caniuse-lite#137]
Hello,

For the Microsoft Edge browser `caniuse-lite` provides only versions up to 126. But `caniuse-db` already has versions up to 130. Please, update the DB.

**Comment by ai** [comment]
We are just repacking [`caniuse-db`](https://github.com/Fyrd/caniuse), ask them (but it is better to wait)

**Comment by ivanovych666** [comment]
Sorry maybe I'm missing something. But as I mentioned in the description, `caniuse-db` already has these new versions, and they have it for a long time. Also, I was cloned yor repo and executed the "pack" script, in the resulted dist all versions exists as expected.

**Comment by ai** [comment]
We automatically release `caniuse-lite` every time when `caniuse-db` was released.

And I see Edge 127 on https://browsersl.ist/#q=edge+127

Maybe you have old `caniuse-lite`?

**Comment by ivanovych666** [comment]
You are right, I made a mistake somewhere. I have created a scratch project and everything looks good. Thank you.
