### ISSUE TITLE
License not recommended for software?

### ISSUE THREAD

**Issue by gavingmiller** [browserslist/caniuse-lite#40]
The description for [CC Attribution 4.0 Int on GitHub](https://github.com/ben-eb/caniuse-lite/blob/e5aa874b3a242dc7970e9887bce8a79bb5f0c506/LICENSE) reads as:

> Permits almost any use subject to providing credit and license notice. Frequently used for media assets and educational materials. The most common license for Open Access scientific publications. Not recommended for software.

_Not recommended for software_ is a bit concerning considering this is attached to a piece of software. Is there a better license that this project can be released under? If not, can you speak to why this license was selected and the implications of using it in a project? 

Thanks!

**Comment by ai** [comment]
`caniuse-db` uses this license, since they contain JSON data only.

Since we are just repack of `caniuse-db` we are using the same license.

Technically, `caniuse-lite` is 90% of JSON and only 10% of unpacking scripts.

I think it is not critical to uses non-software license in this case. Software licenses are good since they are clearify complicated moments. But it doesn't mean that you can use non-software licenses. It means only that there is more gray zones.

**Comment by ai** [comment]
This problem will be fixed during our [Loshadka project](https://github.com/browserslist/browserslist/issues/432).

Right now we are collecting money for this project on [Open Collective](https://opencollective.com/browserslist). If licensing is a problem for your company (it is great that you are doing license review) feel free to donate to fix the problem faster (we will add corporate tiers soon).

**Comment by mifi** [comment]
I'm not sure if i understand correctly, but I think this means that anyone using create-react-app (which uses caniuse-lite) or any other framework that uses browserlist, and who distributes this as part of their production bundle on a web server, will have to include credits to the creators of the caniuse-lite package somewhere on the produced website?

https://tldrlegal.com/license/creative-commons-attribution-4.0-international-(cc-by-4)

**Comment by ai** [comment]
@mifi unfortunately, this is Can I Use database license. We can’t change the license in our repack. Ask them to change the license.

**Comment by mifi** [comment]
I see there has been a discussion about this already. https://github.com/Fyrd/caniuse/issues/4062
I will take the discussion at create-react-app which is my dependent on caniuse-lite.
