### ISSUE TITLE
Is "1.0.30000967" is no more a valid version?

### ISSUE THREAD

**Issue by phani17c** [browserslist/caniuse-lite#41]
Hey, Right now I am building a angular application and when I build my application using "@angular-devkit/build-angular": "0.803.21"  It is using  "@babel/preset-env": "7.7.6" which use  "browserslist": "^4.6.0" which uses "caniuse-lite": "1.0.30000967". So it throws an error that says:

"ERROR: Error: Browserslist: caniuse-lite is outdated. Please run next command `npm update`"

but I think there is no latest version for angular devkit other than I mentioned above.

**Comment by ai** [comment]
Maybe you have different `caniuse-lite` versions in your `node_modiles`.

Call `npm ls | grep browserslist`.

**Comment by phani17c** [comment]
Idk I am hoping this is a fix for angular devkit. I have raised a ticket there https://github.com/angular/angular-cli/issues/16560
