### ISSUE TITLE
Region data and release versions do not match for "and_chr"

### ISSUE THREAD

**Issue by csvn** [browserslist/caniuse-lite#45]
Hi,

I'm using `caniuse-lite` to create a summary of usage % for the browser support targets we are currently aiming for. I'm using the `release_date` property on the agents to create a list of versions to summarize usage for.

I noticed that `'and_chr'` is behaving a bit oddly though. It's  only tracking data for one version (not the weird part), but the version in `release_date` and the version in the usage data do not match. The `release_date` seems to show the latest version and it's release date, but the usage is always summarized under the version key `'0'`. Is this intended? The "regular" agents/browsers (e.g. Chrome/Firefox/Safari/Edge/IE) did not show any weird or similar behavior.

```ts
import { agents, region } from 'caniuse-lite';
import ww from 'caniuse-lite/data/regions/alt-ww.js';

agents['and_chr'].release_date;
// { "79": 1575936000 }
region(ww)['and_chr'];
// { "0": 34.422267 }
```

> https://stackblitz.com/edit/js-zcjlru

**Comment by ai** [comment]
Yeap. Unfortunately, we receiving this data from `caniuse-db` and right now we are just proxy for Can I Use data without changing them.

1. You could ask them, but Can I Use doesn’t want to change data.
2. Another way is to help us with [funding for big `caniuse-lite` refactoring](https://opencollective.com/browserslist), which could will help us fixing Can I Use data.

**Comment by csvn** [comment]
Thanks for your response. I didn't know it was an `caniuse-db` issue, I thought it might have been one of the transforms applied to the data for minification.

**Comment by csvn** [comment]
It's not huge issue, it's not too hard to work around. It was mostly unexpected and a bit of a "rough edge".
