### ISSUE TITLE
Link to features

### ISSUE THREAD

**Issue by piranna** [browserslist/caniuse-lite#48]
Add a comment on each feature file with a link to the actual feature page, so it's possible to find them searching by text in the source code files. Related to https://github.com/ben-eb/caniuse-lite/issues/47

**Comment by ai** [comment]
The idea of this package is to be very compact in your `node_modules`.

I will need a very good and popular use case for increasing file size.

**Comment by piranna** [comment]
Ok, I understand. The idea here, being a comment, it would not be included in final bundles when minified, and would provide some context when using it.

**Comment by ai** [comment]
We have put airway pre-build files to the repo. There is no sources.

Also, file names copy the Can I Use URL. At least during Autoprefixer development I never had an problem of converting URL to the file name.

I think files, which you asked about in other issue really missed for some reason.
