### ISSUE TITLE
TypeError: Cannot read property 'prefix_exceptions' of undefined

### ISSUE THREAD

**Issue by ycjcl868** [browserslist/caniuse-lite#70]
Version: 1.0.30001225

**Comment by gary-Shen** [comment]
The same problem.
It seems that agents module exports with an extra [`agents` ](https://github.com/browserslist/caniuse-lite/blob/main/src/unpacker/agents.js#L12)field.

The index.js alse has an [`agents`](https://github.com/browserslist/caniuse-lite/blob/main/src/unpacker/index.js#L1)

**Comment by ai** [comment]
The fix was released in 1.0.30001226

**Comment by zhangyuang** [comment]
yeah, same problem

**Comment by CastileMan** [comment]
emm..

**Comment by CastileMan** [comment]
> @CastileMan was it fixed in 1.0.30001226?

yes
