### ISSUE TITLE
1.0.30001226 - An unhandled exception occurred: Cannot read property 'prefix_exceptions' of undefined

### ISSUE THREAD

**Issue by Droidlover** [browserslist/caniuse-lite#74]
Hi there, facing the below error : 

`An unhandled exception occurred: Cannot read property 'prefix_exceptions' of undefined
`
Tried version  : 1.0.30001225 and 1.0.30001226

Saw 1.0.30001227 may fix this, but it isn't available on NPM. Can someone please help here?

Thanks

**Comment by xqin** [comment]
https://github.com/browserslist/caniuse-lite/issues/70

**Comment by Droidlover** [comment]
Fixed now.
