### ISSUE TITLE
Android Edge Chromium needs to be a separate class "and_edge"

### ISSUE THREAD

**Issue by GaryHyland** [browserslist/caniuse-lite#76]
Currently seems to get lumped in as Edge.
Current Edge (edge-chromimium) on desktop is 90.
Current Edge Chromium on Android is 46.

This REALLY throws the version checking out. Need another browser defined - and_edge?
This would seem to follow the pattern for chrome, although the windows and android version both seem to be on v90 at present.

**Comment by ai** [comment]
This repo is just for repack of [`caniuse-db`](https://github.com/leecade/caniuse-db). You need to send requests like this to Can I Use
