### ISSUE TITLE
opera version looks too old

### ISSUE THREAD

**Issue by pastak** [browserslist/caniuse-lite#79]
I use it by `browserslist` with db version 1.0.30001230.
```
$ npm exec browserslist "last 2 Opera major versions"
opera 73
opera 72
```
Opera's latest version is 73 but currently Opera's real last version is 76.

Can I help to update?

**Comment by ai** [comment]
1. Run `npx browserslist@latest --update-db`. Your version is not latest.
2. Anyway, we can’t update it. We use data from Can I Use.
