### ISSUE TITLE
css-filters has not backdrop-filter

### ISSUE THREAD

**Issue by 282159468** [browserslist/caniuse-lite#80]
backdrop-filter
![image](https://user-images.githubusercontent.com/28442945/124255243-8896f200-db5c-11eb-8a5e-000ffc9bd138.png)

css-filters has not backdrop-filter, so when i exec 

t.less
.test {
  backdrop-filter: blur(2px);
}

doiuse --browsers "chrome 71" t.less
get message "[css-tokenize] unfinished business [ [ 'root' ] ]", has not error

**Comment by ai** [comment]
We just repack Can I Use data. You need to open issue there.
