### ISSUE TITLE
breaking change in v1.0.30001224

### ISSUE THREAD

**Issue by ljharb** [browserslist/caniuse-lite#81]
https://unpkg.com/browse/caniuse-lite@1.0.30001224/dist/unpacker/agents.js uses object destructuring, which breaks in node 4.

https://unpkg.com/browse/caniuse-lite@1.0.30001223/dist/unpacker/agents.js does not use it.

This is a breaking change in a patch version - v1 must always work on node 4. Please revert the untranspiled object destructuring.

**Comment by ai** [comment]
`caniuse-lite` didn’t supported Node.js 4. Our minimal Node.js version is 6. https://github.com/browserslist/caniuse-lite/blob/main/.github/workflows/test.yml

If you have an important use case to support Node.js 4, you can send PR.

**Comment by ljharb** [comment]
It worked on node 4 before, and there's no "engines" field. What you tested on is irrelevant.

Sure, I can send a PR.

**Comment by ljharb** [comment]
Looks like https://github.com/browserslist/caniuse-lite/commit/2f887afcd3a37d24fd109fba0f26c73251a650ff was the culprit - updating babel 6 to babel 7 is almost never a non-breaking change. I'll see if I can keep babel 7 but tweak the config so it properly supports what v1.0.0 supported.

**Comment by ai** [comment]
> What you tested on is irrelevant. Without an "engines" field, what's supported is "whatever it works on".

This is not a definition of public API. Tests show what do we care about.

**Comment by ljharb** [comment]
@ai you don't have a prepublish script, and i can't figure out how babel is invoked at all. can you give me some guidance?

**Comment by ljharb** [comment]
@ai tests aren't documentation. The reality is that you broke consumers, and babel will be forced to pin to v1.0.3.0001223 for the duration of v7 unless this is fixed.

**Comment by ai** [comment]
> you don't have a prepublish script, and i can't figure out how babel is invoked at all. can you give me some guidance?

We use GitHub Actions to chcek `caniuse-db` updates and re-pack it https://github.com/browserslist/caniuse-lite/blob/main/.github/workflows/check.yml#L34

**Comment by ljharb** [comment]
OK - where does the "pack" script put its files? what babel config does it read?

**Comment by ai** [comment]
We do not use Babel to compile sources. Only as AST to generate new JS files.

Change this file directly https://github.com/browserslist/caniuse-lite/blob/main/dist/unpacker/agents.js

(Yeap, the dir is called `dist/` like it is auto-generated, but we were forced to keep the old name for backward compatibility.)

**Comment by ljharb** [comment]
OK, let's see how #82 works out :-)

**Comment by ai** [comment]
New version will be released on new `caniuse-db` release

**Comment by ljharb** [comment]
Awesome, thank you!
