### ISSUE TITLE
Please push tags

### ISSUE THREAD

**Issue by Natureshadow** [browserslist/caniuse-lite#84]
The tags pushed to GitHub seem outdated, breaking the watch mechanism in Debian to keep the package updated.

Please push the tags for all versions.

**Comment by ai** [comment]
`caniuse-lite` does automatically by GitHub Actions https://github.com/browserslist/caniuse-lite/blob/main/.github/workflows/check.yml

I am OK with adding git tags, but you need to change script in PR. I spend all my free time on other projects.
