### ISSUE TITLE
versions greater than 1.0.30001349 break my PWA for some reason

### ISSUE THREAD

**Issue by ssuess** [browserslist/caniuse-lite#96]
Hi, I am trying to troubleshoot an issue I am having with my PWA no longer loading if I update caniuse-lite to version later than 1.0.30001349. If I stay on 1.0.30001349, my PWA will load fine, and service worker will be able to update it to new versions, etc. But if I am using later versions of this package, I get syntax or MIME type errors and the page is blank and won't load. Any suggestions for how to fix this? Thanks

**Comment by ai** [comment]
Maybe it is related with https://github.com/browserslist/browserslist/issues/698
