### ISSUE TITLE
Error while installing caniuse-lite.

### ISSUE THREAD

**Issue by mugishap** [browserslist/caniuse-lite#98]
Greetings, I'm encountering an error while using vite +react + ts where I am told to install caniuse-lite. I tried to install it but I am getting an error saying the it is an invalid version.
I used the command below
>npm i caniuse-lite

And I am getting this error
>npm ERR! Invalid Version:

**Comment by mugishap** [comment]
Anyone who can help with the error can ping me via my socials in my profile or list it below

**Comment by ai** [comment]
Seems like you have a network error or maybe very old npm

**Comment by mugishap** [comment]
Thanks for the help. Let me check and see
